export enum ChannelId {
  Facebook = 'facebook',
  Skype = 'skype',
  Msteams = 'msteams',
  Telegram = 'telegram',
  Kik = 'kik',
  Email = 'email',
  Slack = 'slack',
  Groupme = 'groupme',
  Sms = 'sms',
  Emulator = 'emulator',
  Directline = 'directline',
  Webchat = 'webchat',
  Console = 'console',
  Cortana = 'cortana',
}
